[package]
name = "blocking"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.2.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2021"
rust-version = "1.57"
description = "A thread pool for isolating blocking I/O in async programs"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/blocking"
keywords = ["async", "file", "stdio", "stdin", "process"]
categories = ["asynchronous", "concurrency"]
exclude = ["/.*"]

[dependencies]
async-oneshot = "0.5"
once_cell = "1.4.1"

[dev-dependencies]
futures-lite = "1.11.0"
